version: '3.4'

services:
  bookdemoweb:
    ports:
      - "30000:80"
    image: ${DOCKER_REGISTRY-}bookdemoweb
    build:
      context: .
      dockerfile: DomainCentricDemo.Web/Dockerfile
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "http://+:80"
      "ConnectionStrings:DefaultConnection": "Server=host.docker.internal;Database=BookDbUsers;User Id=docker; Password=docker1234;Trusted_Connection=False;MultipleActiveResultSets=true; TrustServerCertificate=true"

  bookweb-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd", "-app-id", "bookdemoweb", "-app-port", "80"]
    depends_on:
      - bookdemoweb
    network_mode: "service:bookdemoweb" 


  weatherdemoapi:
    ports:
      - "30001:80"
    image: ${DOCKER_REGISTRY-}weatherdemoapi
    build:
      context: .
      dockerfile: DemoApi/Dockerfile
    environment:    
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "http://+:80"

  weatherservice-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd", "-app-id", "weatherdemoapi", "-app-port", "80"]
    depends_on:
      - weatherdemoapi
    network_mode: "service:weatherdemoapi" 


  bookdemoapi:
    ports:
      - "30002:80"
    image: ${DOCKER_REGISTRY-}bookdemoapi
    build:
      context: .
      dockerfile: DomainCentricDemo.Api/Dockerfile
    environment:    
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "http://+:80"
      "ConnectionStrings:BookConnectionString": "Server=host.docker.internal;Database=BookDb;User Id=docker; Password=docker1234;Trusted_Connection=False;MultipleActiveResultSets=true; TrustServerCertificate=true"
 
  bookservice-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd", "-app-id", "bookdemoapi", "-app-port", "80"]
    depends_on:
      - bookdemoapi
    network_mode: "service:bookdemoapi" 
